apiVersion: v1
data:
  DATABASE_URL: postgresql+psycopg2://yeeter_user:yeeter_pw@postgres:5432/hl7_yeeter_db
  FLASK_ENV: production
  JWT_ACCESS_TOKEN_EXPIRES_HOURS: "24"
  VITE_API_URL: https://yeet.trazen.org
  VITE_SOCKET_URL: https://yeet.trazen.org
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DATABASE_URL":"postgresql+psycopg2://yeeter_user:yeeter_pw@postgres:5432/hl7_yeeter_db","FLASK_ENV":"production","JWT_ACCESS_TOKEN_EXPIRES_HOURS":"24","VITE_API_URL":"https://yeet.trazen.org","VITE_SOCKET_URL":"https://yeet.trazen.org"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"yeeter-config","namespace":"yeeter"}}
  creationTimestamp: "2025-10-21T14:23:45Z"
  name: yeeter-config
  namespace: yeeter
  resourceVersion: "39148"
  uid: 1b92e1f1-cd27-4bd0-85c8-43a6ad9838e0
