apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: yeeter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # k3s default storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yeeter-data
  namespace: yeeter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
