apiVersion: v1
data:
  GOOGLE_API_KEY: QUl6YVN5RFcxSTFmTFR6UDk1eWdvM2lOLURJc042RzBxb1g4dXZV
  JWT_SECRET_KEY: NzA0MWUyYzE2MjUyMmEzZTUwM2U5YzIwYzAwYWU3YzdlZjY0MjQzZTRjNjFiNTE0
  POSTGRES_DB: aGw3X3llZXRlcl9kYg==
  POSTGRES_PASSWORD: eWVldGVyX3B3
  POSTGRES_USER: eWVldGVyX3VzZXI=
  VITE_GOOGLE_CLIENT_ID: NTYxMTcyMTQ0ODA1LWFuOWs5MDIxYnJuaWpsZWJ1M2JxM24wNGpyM2lyaXFjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"GOOGLE_API_KEY":"QUl6YVN5RFcxSTFmTFR6UDk1eWdvM2lOLURJc042RzBxb1g4dXZV","JWT_SECRET_KEY":"NzA0MWUyYzE2MjUyMmEzZTUwM2U5YzIwYzAwYWU3YzdlZjY0MjQzZTRjNjFiNTE0","POSTGRES_DB":"aGw3X3llZXRlcl9kYg==","POSTGRES_PASSWORD":"eWVldGVyX3B3","POSTGRES_USER":"eWVldGVyX3VzZXI=","VITE_GOOGLE_CLIENT_ID":"NTYxMTcyMTQ0ODA1LWFuOWs5MDIxYnJuaWpsZWJ1M2JxM24wNGpyM2lyaXFjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t"},"kind":"Secret","metadata":{"annotations":{},"name":"yeeter-secrets","namespace":"yeeter"},"type":"Opaque"}
  creationTimestamp: "2025-10-21T14:23:45Z"
  name: yeeter-secrets
  namespace: yeeter
  resourceVersion: "33408"
  uid: eb12ab80-aa70-4f8a-9b97-a39c69432aa0
type: Opaque
